### PR TITLE
Renames docker image to zipkin, as it isn't ambiguous

### PR DESCRIPTION
**Pull request by codefromthecrypt**
Moving forward, we have a single docker image. Instead of a suffix, we
can standardize on the simple word "zipkin"

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
cc @abesto @klingerf @gena01 @adrianco

**Comment by eirslett** [comment]
+1

**Comment by codefromthecrypt** [comment]
re-cutting 1.1.2

**Comment by codefromthecrypt** [comment]
forgot to add repos on quay.io and dockerhub. cutting release again

**Pull request merged**
